bus stop json, dataValidate
SlugLoopCSE115a/SlugLoop pull request #9
Opened 2023-05-19 06:07 UTC by igpang

Placed the validate data as a function
added a new json file with all the bus stops latitude and longitude

2023-05-20 03:01 UTC, IdkwhatImD0ing requested changes

2023-05-20 03:01 UTC, IdkwhatImD0ing commented on server/routes/bus-stops.json
Please add keys that labels each position with its matching bus stop. It's hard to know which position is which bus stop atm.

2023-05-20 03:29 UTC, igpang commented on server/routes/bus-stops.json
Added simple labels for each stop

2023-05-24 18:58 UTC, IdkwhatImD0ing reviewed
Where are the bus stops shown?

It might be better to use the existing bus marker instead of a new one, see if you can render text right above the coordinates of the current bus markers. For example <next loop in: xxx>

2023-05-26 18:13 UTC, IdkwhatImD0ing approved these changes

2023-05-26 18:13 UTC, merged